name-template: "ðŸš€ DexScraper $NEXT_TAG"
tag-template: "$NEXT_TAG"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "ðŸ› Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "ðŸ§° Maintenance"
    labels:
      - "chore"
      - "ci"
      - "dependencies"
      - "dep"
      - "deps"
      - "docs"
      - "refactor"
      - "test"
      - "tests"
  - title: "Other Changes"
    labels: []

exclude-labels:
  - "skip-changelog"
  - "no-changelog"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "bug"
      - "fix"
      - "chore"
      - "ci"
      - "dependencies"
      - "docs"
      - "refactor"
      - "test"
      - "tests"
  default: patch

template: |
  ## ðŸ‘» DexScraper Release $NEXT_TAG

  > âš ï¸ **RESEARCH & EDUCATIONAL PURPOSE ONLY** âš ï¸
  > This project has **NO AFFILIATION** with DexScreener. Use at your own risk.

  ### ðŸŽ‰ What's New
  $CHANGES

  ### ðŸ‘¥ Contributors
  $CONTRIBUTORS
