name-template: "ðŸš€ DexScraper $NEXT_TAG"
tag-template: "$NEXT_TAG"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "ðŸ› Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "ðŸ§° Maintenance"
    labels:
      - "perf"
      - "chore"
      - "ci"
      - "build"
      - "dependencies"
      - "dep"
      - "deps"
      - "docs"
      - "refactor"
      - "test"
      - "tests"
  - title: "Other Changes"
    labels:
      - "other"

exclude-labels:
  - "skip-changelog"
  - "no-changelog"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "perf"
      - "chore"
      - "ci"
      - "build"
      - "dependencies"
      - "dep"
      - "deps"
      - "docs"
      - "refactor"
      - "test"
      - "tests"
      - "other"
  default: patch

autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?:/i'
  - label: "feature"
    title:
      - '/^feature(\(.+\))?:/i'
  - label: "enhancement"
    title:
      - '/^enhancement(\(.+\))?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?:/i'
  - label: "bug"
    title:
      - '/^bug(\(.+\))?:/i'
  - label: "perf"
    title:
      - '/^perf(\(.+\))?:/i'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?:/i'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?:/i'
  - label: "build"
    title:
      - '/^build(\(.+\))?:/i'
  - label: "ci"
    title:
      - '/^ci(\(.+\))?:/i'
  - label: "test"
    title:
      - '/^test(\(.+\))?:/i'
  - label: "tests"
    title:
      - '/^tests(\(.+\))?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?:/i'
  - label: "dep"
    title:
      - '/^dep(\(.+\))?:/i'
  - label: "deps"
    title:
      - '/^deps(\(.+\))?:/i'
  - label: "dependencies"
    title:
      - '/^dependencies(\(.+\))?:/i'
  - label: "other"
    title:
      - '/.*/'

template: |
  ## ðŸ‘» DexScraper Release $NEXT_TAG

  > âš ï¸ **RESEARCH & EDUCATIONAL PURPOSE ONLY** âš ï¸
  > This project has **NO AFFILIATION** with DexScreener. Use at your own risk.

  ### ðŸŽ‰ What's New
  $CHANGES

  ### ðŸ‘¥ Contributors
  $CONTRIBUTORS
